import type { CapabilitiesResult } from "@threadwake/contracts";

export const TOOL_NAMES = {
  capabilities: "threadwake_get_capabilities",
  list: "threadwake_list_work_units",
  get: "threadwake_get_work_unit",
  search: "threadwake_search_work_units",
  evidence: "threadwake_get_evidence",
  preview: "threadwake_preview_fixture_change",
  confirm: "threadwake_confirm_fixture_change",
  undo: "threadwake_undo_fixture_change",
} as const;

export const TOOL_CAPABILITIES: CapabilitiesResult["tools"] = [
  {
    name: TOOL_NAMES.capabilities,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.list,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.get,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.search,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.evidence,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.preview,
    readOnly: true,
    destructive: false,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: false,
    idempotent: true,
    reversible: false,
  },
  {
    name: TOOL_NAMES.confirm,
    readOnly: false,
    destructive: true,
    openWorld: false,
    requiresPreview: true,
    requiresConfirmation: true,
    idempotent: true,
    reversible: true,
  },
  {
    name: TOOL_NAMES.undo,
    readOnly: false,
    destructive: true,
    openWorld: false,
    requiresPreview: false,
    requiresConfirmation: true,
    idempotent: true,
    reversible: false,
  },
];
